name: Benchmarks
on:
  push:

jobs:
  bench:
    name: Build nikos
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: DataDog/nikos

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build nikos
        run: bash .ci_build/build_install_nikos.sh .

      - name: Run bench
        env:
          HOST_ETC: ${{ github.workspace }}/fixtures/rhel
        run: /usr/bin/time -v /opt/nikos/bin/nikos download --kernel 3.10.0-1160.2.1.el7.x86_64 --family rhel --platform centos
